
export const ATTEMPT_LOGIN = "USER_ATTEMPT_LOGIN";
export const ON_LOGIN_STARTED = "USER_ATTEMPT_LOGIN_STARTED";
export const ON_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const ON_LOGIN_FAILED = "USER_LOGIN_FAIL";

